import QtQuick

QtObject {

    property ListModel julyMailsModel: ListModel {
        ListElement { sender: "eBay"; subject: "Here are your new eBay weekly deals!"; content: "Vegan excepteur banjo, sustainable iceland quinoa do flexitarian la croix enamel pin succulents tacos. Single-origin coffee listicle polaroid pok pok pickled man braid af craft beer hashtag fam venmo squid man bun." }
        ListElement { sender: "Paul Stewart"; subject: "Ne docendi mentitum legendos eam"; content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin rutrum vitae felis vitae volutpat. Fusce aliquam, nulla eget sodales maximus, nulla urna vulputate mauris, vel ultricies ante lacus id odio. Mauris blandit felis ipsum, sed bibendum dolor placerat ut. Nunc facilisis vehicula nisl, ut efficitur urna varius ac. Quisque posuere diam quis sapien rhoncus ornare. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nunc condimentum libero a dui tristique venenatis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.

Ut ultricies purus tellus, non pharetra felis sagittis at. Quisque convallis ipsum nisl, et placerat velit condimentum id. Nam vehicula turpis ac lorem scelerisque, a congue metus ullamcorper. Aliquam in elit a libero pellentesque aliquam at ac dolor. Morbi sit amet velit in eros sagittis semper at a diam. Sed ut lectus ante. Sed sit amet consequat nisi. Quisque non finibus purus. Aenean vel arcu volutpat, mattis sapien id, vestibulum ligula. In congue blandit lacus id vestibulum. Proin eget lacus venenatis, vehicula libero id, porta nulla. Fusce eu elit in metus gravida cursus eu sit amet dui. Duis et aliquam nisi, in mattis nisi. Nulla tristique neque ut odio gravida porta. Ut in felis nec odio euismod maximus. Curabitur eget felis sed erat sagittis tristique vel nec nisl. Nullam ac interdum purus, eu mollis mauris. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec viverra molestie nibh, eget ultrices est elementum non." }
        ListElement { sender: "Dr. Maria Mayers"; subject: "Resolution diminution conviction"; content: "Flexitarian wayfarers lo-fi pok pok cupidatat. Pariatur ramps vaporware cupidatat unicorn. Kitsch organic et officia tote bag sustainable retro flexitarian velit deep v photo booth non drinking vinegar in. Veniam." }
        ListElement { sender: "eBay"; subject: "Here are your new eBay weekly deals! "; content: "Expect warmly its tended garden him esteem had remove off." }
    }

    property ListModel juneMailsModel: ListModel {
        ListElement { sender: "eBay"; subject: "Here are your new eBay weekly deals!"; content: "Vegan excepteur banjo, sustainable iceland quinoa do flexitarian la croix enamel pin succulents tacos. Single-origin coffee listicle polaroid pok pok pickled man braid af craft beer hashtag fam venmo squid man bun." }
        ListElement { sender: "Dr. Simon Phillips"; subject: "Ne docendi mentitum legendos eam"; content: "Vaporware leggings laboris meggings salvia normcore. Enamel pin whatever VHS, ramps pinterest you probably haven't heard of them meh austin. Kickstarter asymmetrical paleo, polaroid vegan retro lyft coloring." }
    }

    property ListModel mayMailsModel: ListModel {
        ListElement { sender: "eBay"; subject: "Here are your new eBay weekly deals!"; content: "Vegan excepteur banjo, sustainable iceland quinoa do flexitarian la croix enamel pin succulents tacos. Single-origin coffee listicle polaroid pok pok pickled man braid af craft beer hashtag fam venmo squid man bun." }
        ListElement { sender: "Dr. Simon Phillips"; subject: "Ne docendi mentitum legendos eam"; content: "Vaporware leggings laboris meggings salvia normcore. Enamel pin whatever VHS, ramps pinterest you probably haven't heard of them meh austin. Kickstarter asymmetrical paleo, polaroid vegan retro lyft coloring." }
    }

    property ListModel aprilMailsModel: ListModel {
        ListElement { sender: "eBay"; subject: "Here are your new eBay weekly deals!"; content: "Vegan excepteur banjo, sustainable iceland quinoa do flexitarian la croix enamel pin succulents tacos. Single-origin coffee listicle polaroid pok pok pickled man braid af craft beer hashtag fam venmo squid man bun." }
        ListElement { sender: "Paul Stewart"; subject: "Ne docendi mentitum legendos eam"; content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin rutrum vitae felis vitae volutpat. Fusce aliquam, nulla eget sodales maximus, nulla urna vulputate mauris, vel ultricies ante lacus id odio. Mauris blandit felis ipsum, sed bibendum dolor placerat ut. Nunc facilisis vehicula nisl, ut efficitur urna varius ac. Quisque posuere diam quis sapien rhoncus ornare. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nunc condimentum libero a dui tristique venenatis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.

Ut ultricies purus tellus, non pharetra felis sagittis at. Quisque convallis ipsum nisl, et placerat velit condimentum id. Nam vehicula turpis ac lorem scelerisque, a congue metus ullamcorper. Aliquam in elit a libero pellentesque aliquam at ac dolor. Morbi sit amet velit in eros sagittis semper at a diam. Sed ut lectus ante. Sed sit amet consequat nisi. Quisque non finibus purus. Aenean vel arcu volutpat, mattis sapien id, vestibulum ligula. In congue blandit lacus id vestibulum. Proin eget lacus venenatis, vehicula libero id, porta nulla. Fusce eu elit in metus gravida cursus eu sit amet dui. Duis et aliquam nisi, in mattis nisi. Nulla tristique neque ut odio gravida porta. Ut in felis nec odio euismod maximus. Curabitur eget felis sed erat sagittis tristique vel nec nisl. Nullam ac interdum purus, eu mollis mauris. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec viverra molestie nibh, eget ultrices est elementum non." }
        ListElement { sender: "Dr. Maria Mayers"; subject: "Resolution diminution conviction"; content: "Flexitarian wayfarers lo-fi pok pok cupidatat. Pariatur ramps vaporware cupidatat unicorn. Kitsch organic et officia tote bag sustainable retro flexitarian velit deep v photo booth non drinking vinegar in. Veniam." }
        ListElement { sender: "eBay"; subject: "Here are your new eBay weekly deals! "; content: "Expect warmly its tended garden him esteem had remove off." }
    }
}
